/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Agents.TorreControlo;
import jade.gui.GuiEvent;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author PEDRO
 */
public class Principal extends javax.swing.JFrame {

    private TorreControlo myAgent;
    private ArrayList<String> airp;
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setIcon();
        
        //fact arrival
        this.fact.setEnabled(false);
        this.metlabel.setEnabled(false);
        this.oculabel.setEnabled(false);
        this.priorilabel.setEnabled(false);
        this.met.setEnabled(false);
        this.ocup.setEnabled(false);
        this.priori.setEnabled(false);
        this.factArrival.setEnabled(false);
        
        //default revision
        this.defa.setEnabled(false);
        this.metlabeldef.setEnabled(false);
        this.ocuplabeldef.setEnabled(false);
        this.priorilabeldef.setEnabled(false);
        this.metdef.setEnabled(false);
        this.ocupdef.setEnabled(false);
        this.prioridef.setEnabled(false);
        this.defaultRevision.setEnabled(false);

    }
    
    public Principal(TorreControlo t){
        initComponents();
        setIcon();
        this.myAgent = t;
        //povoaAvioes();
        
        //fact arrival
        this.fact.setEnabled(false);
        this.metlabel.setEnabled(false);
        this.oculabel.setEnabled(false);
        this.priorilabel.setEnabled(false);
        this.met.setEnabled(false);
        this.ocup.setEnabled(false);
        this.priori.setEnabled(false);
        this.factArrival.setEnabled(false);
        
        //default revision
        this.defa.setEnabled(false);
        this.metlabeldef.setEnabled(false);
        this.ocuplabeldef.setEnabled(false);
        this.priorilabeldef.setEnabled(false);
        this.metdef.setEnabled(false);
        this.ocupdef.setEnabled(false);
        this.prioridef.setEnabled(false);
        this.defaultRevision.setEnabled(false);
    }
    
    public void imprimeText(String s){
        this.speculative.append(s);
        this.speculative.append("\n");
    }
    
    public void imprimeList(List<String> s){
        for(String st: s){
            this.speculative.append(st);
            this.speculative.append("\n");
        }
    }
    
    
    public ArrayList povoaAvioes(){
        ArrayList<String> ec = (ArrayList<String>) myAgent.daAviao(airp);
        DefaultListModel list =  new DefaultListModel();
        for(String s: ec){
            list.addElement(s);
        }
        this.listaAirplanes.setModel(list);
        System.out.println(myAgent.airplanes);

        return ec;
        
    }
    
    public void avisa(){
        JOptionPane.showMessageDialog(null, "Esse aviao já existe");
    }
    
    public void avisaPositivo(String nome){
        JOptionPane.showMessageDialog(null,"Airplane " +nome+ " foi criado com sucesso");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        speculative = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaAirplanes = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        nameAirplane = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        fact = new javax.swing.JPanel();
        metlabel = new javax.swing.JLabel();
        met = new javax.swing.JComboBox<>();
        oculabel = new javax.swing.JLabel();
        ocup = new javax.swing.JComboBox<>();
        priorilabel = new javax.swing.JLabel();
        priori = new javax.swing.JComboBox<>();
        factArrival = new javax.swing.JButton();
        defa = new javax.swing.JPanel();
        metlabeldef = new javax.swing.JLabel();
        metdef = new javax.swing.JComboBox<>();
        ocuplabeldef = new javax.swing.JLabel();
        ocupdef = new javax.swing.JComboBox<>();
        priorilabeldef = new javax.swing.JLabel();
        prioridef = new javax.swing.JComboBox<>();
        defaultRevision = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Airplane Departures Decision Support System");
        getContentPane().setLayout(null);

        speculative.setColumns(20);
        speculative.setRows(5);
        jScrollPane1.setViewportView(speculative);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 310, 550, 160);

        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(890, 510, 100, 30);

        jScrollPane2.setViewportView(listaAirplanes);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(40, 110, 210, 130);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Airplane Departures");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 80, 210, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Welcome to Airplane Departures Decision Support System");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 20, 620, 50);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Speculativa Departures");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 280, 550, 20);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/logo.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(850, 20, 160, 140);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Create Airplane"));

        jLabel7.setText("Name of the Airplane");

        nameAirplane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameAirplaneActionPerformed(evt);
            }
        });

        jButton2.setText("Create Airplane");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(nameAirplane, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jButton2)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameAirplane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(280, 100, 210, 140);

        fact.setBorder(javax.swing.BorderFactory.createTitledBorder("Fact Arrival"));

        metlabel.setText("Meteorology");

        met.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------", "t0", "t1", "t2" }));

        oculabel.setText("Track Occupation");

        ocup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------", "o1", "o2" }));
        ocup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ocupActionPerformed(evt);
            }
        });

        priorilabel.setText("Priority");

        priori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------", "p0", "p1" }));

        factArrival.setText("Fact Arrival");
        factArrival.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factArrivalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout factLayout = new javax.swing.GroupLayout(fact);
        fact.setLayout(factLayout);
        factLayout.setHorizontalGroup(
            factLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(factLayout.createSequentialGroup()
                .addGroup(factLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(metlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oculabel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priorilabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(met, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(factLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(factArrival, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                        .addComponent(priori, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ocup, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 36, Short.MAX_VALUE))
        );
        factLayout.setVerticalGroup(
            factLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(factLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(metlabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(met, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(oculabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ocup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(priorilabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(priori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(factArrival)
                .addGap(0, 32, Short.MAX_VALUE))
        );

        getContentPane().add(fact);
        fact.setBounds(610, 210, 170, 260);

        defa.setBorder(javax.swing.BorderFactory.createTitledBorder("Default Revision"));

        metlabeldef.setText("Meteorology");

        metdef.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------", "t0", "t1", "t2" }));

        ocuplabeldef.setText("Track Occupation");

        ocupdef.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------", "o1", "o2" }));

        priorilabeldef.setText("Priority");

        prioridef.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------", "p0", "p1" }));

        defaultRevision.setText("Default Revision");
        defaultRevision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defaultRevisionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout defaLayout = new javax.swing.GroupLayout(defa);
        defa.setLayout(defaLayout);
        defaLayout.setHorizontalGroup(
            defaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(defaLayout.createSequentialGroup()
                .addGroup(defaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(metlabeldef, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(metdef, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ocuplabeldef)
                    .addComponent(ocupdef, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(priorilabeldef, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prioridef, 0, 105, Short.MAX_VALUE))
                .addGap(0, 63, Short.MAX_VALUE))
            .addGroup(defaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(defaultRevision)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        defaLayout.setVerticalGroup(
            defaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(defaLayout.createSequentialGroup()
                .addComponent(metlabeldef, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(metdef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ocuplabeldef)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ocupdef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(priorilabeldef)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(prioridef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(defaultRevision)
                .addGap(0, 31, Short.MAX_VALUE))
        );

        getContentPane().add(defa);
        defa.setBounds(820, 210, 180, 260);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/22137-airplane-in-the-sunset-1680x1050-aircraft-wallpaper-1024x616.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -10, 1020, 570);

        setBounds(0, 0, 1034, 598);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //if(nameAirplane.getText()){
            nameAirplane.getText();
            System.out.println(nameAirplane.getText());
            GuiEvent ge = new GuiEvent(nameAirplane.getText(),1);
            this.myAgent.postGuiEvent(ge);
            String name = nameAirplane.getText();
            nameAirplane.setText("");
            //fact arrival
            this.fact.setEnabled(true);
            this.metlabel.setEnabled(true);
            this.oculabel.setEnabled(true);
            this.priorilabel.setEnabled(true);
            this.met.setEnabled(true);
            this.ocup.setEnabled(true);
            this.priori.setEnabled(true);
            this.factArrival.setEnabled(true);
            
        //}else{
          //  JOptionPane.showMessageDialog(null, "Não inseriu nome!");
        //}
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nameAirplaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameAirplaneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameAirplaneActionPerformed

    private void ocupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ocupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ocupActionPerformed

    private void factArrivalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factArrivalActionPerformed
        // TODO add your handling code here:
        if(!met.getSelectedItem().equals("--------")){
            GuiEvent ge = new GuiEvent("informacao:"+met.getSelectedItem().toString(),1);
            System.out.println("informacao:"+met.getSelectedItem());
            this.myAgent.postGuiEvent(ge);
        }
        else if(!ocup.getSelectedItem().equals("--------")){
            GuiEvent ge = new GuiEvent("informacao:"+ocup.getSelectedItem().toString(),1);
            System.out.println("informacao:"+ocup.getSelectedItem());
            this.myAgent.postGuiEvent(ge);
        }
        else if(!priori.getSelectedItem().equals("--------")){
            GuiEvent ge = new GuiEvent("informacao:"+priori.getSelectedItem().toString(),1);
            System.out.println("informacao:"+priori.getSelectedItem());
            this.myAgent.postGuiEvent(ge);
        }else if((met.getSelectedItem().equals("--------"))&&(ocup.getSelectedItem().equals("--------"))&&(priori.getSelectedItem().equals("--------"))){
            JOptionPane.showMessageDialog(null, "Não selecionou nenhuma chegada de facto");
        }else if((met.getSelectedItem().equals("--------"))||(ocup.getSelectedItem().equals("--------"))||(priori.getSelectedItem().equals("--------"))){
            JOptionPane.showMessageDialog(null, "Selecione apenas uma fonte de informação para a chegada de facto");
        }
        //default revision
            this.defa.setEnabled(true);
            this.metlabeldef.setEnabled(true);
            this.ocuplabeldef.setEnabled(true);
            this.priorilabeldef.setEnabled(true);
            this.metdef.setEnabled(true);
            this.ocupdef.setEnabled(true);
            this.prioridef.setEnabled(true);
            this.defaultRevision.setEnabled(true);
    }//GEN-LAST:event_factArrivalActionPerformed

    
    private void defaultRevisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defaultRevisionActionPerformed
        // TODO add your handling code here:
        //if((metdef.getSelectedItem().equals("--------"))&&(ocupdef.getSelectedItem().equals("--------"))&&(prioridef.getSelectedItem().equals("--------"))){
          //  JOptionPane.showMessageDialog(null, "Não selecionou nenhuma revisãod dos valores por defeito");
        //}else if((metdef.getSelectedItem().equals("--------"))||(ocupdef.getSelectedItem().equals("--------"))||(prioridef.getSelectedItem().equals("--------"))){
          //  JOptionPane.showMessageDialog(null, "Selecione apenas uma revisão dos valores por defeito");
         if(!metdef.getSelectedItem().equals("--------")){
            GuiEvent ge = new GuiEvent("revisao:"+metdef.getSelectedItem().toString(),1);
            System.out.println("revisao:"+metdef.getSelectedItem());
            this.myAgent.postGuiEvent(ge);
        }else if(!ocupdef.getSelectedItem().equals("--------")){
            GuiEvent ge = new GuiEvent("revisao:"+ocupdef.getSelectedItem().toString(),1);
            System.out.println("revisao:"+ocupdef.getSelectedItem());
            this.myAgent.postGuiEvent(ge);
        }else if(!prioridef.getSelectedItem().equals("--------")){
            GuiEvent ge = new GuiEvent("revisao:"+prioridef.getSelectedItem().toString(),1);
            System.out.println("informacao:"+prioridef.getSelectedItem());
            this.myAgent.postGuiEvent(ge);
        }
    }//GEN-LAST:event_defaultRevisionActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel defa;
    private javax.swing.JButton defaultRevision;
    private javax.swing.JPanel fact;
    private javax.swing.JButton factArrival;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listaAirplanes;
    private javax.swing.JComboBox<String> met;
    private javax.swing.JComboBox<String> metdef;
    private javax.swing.JLabel metlabel;
    private javax.swing.JLabel metlabeldef;
    private javax.swing.JTextField nameAirplane;
    private javax.swing.JLabel oculabel;
    private javax.swing.JComboBox<String> ocup;
    private javax.swing.JComboBox<String> ocupdef;
    private javax.swing.JLabel ocuplabeldef;
    private javax.swing.JComboBox<String> priori;
    private javax.swing.JComboBox<String> prioridef;
    private javax.swing.JLabel priorilabel;
    private javax.swing.JLabel priorilabeldef;
    private javax.swing.JTextArea speculative;
    // End of variables declaration//GEN-END:variables

private void setIcon() {
    setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Pictures/logo.png")));
}

}
